In [1]:
#SVM on Letters dataset
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm

In [3]:
import os

In [6]:
os.chdir("D:\\Training\\001-RB Data Science\\008_Support Vector Machine\\")

In [7]:
import pandas as pd

In [8]:
letter_df=pd.read_csv('Letters.csv')

In [9]:
letter_df.head()

,letter,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
0,T,2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8
1,I,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
2,D,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
3,N,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
4,G,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10

In [10]:
from sklearn.model_selection import train_test_split

In [12]:
df_y=letter_df.loc[:,'letter']

In [13]:
letter_df.columns

Index(['letter', 'xbox', 'ybox', 'width', 'height', 'onpix', 'xbar', 'ybar',
       'x2bar', 'y2bar', 'xybar', 'x2ybar', 'xy2bar', 'xedge', 'xedgey',
       'yedge', 'yedgex'],
      dtype='object')

In [14]:
df_x=letter_df.loc[:,['xbox', 'ybox', 'width', 'height', 'onpix', 'xbar', 'ybar',
       'x2bar', 'y2bar', 'xybar', 'x2ybar', 'xy2bar', 'xedge', 'xedgey',
       'yedge', 'yedgex']]

In [15]:
X_train, X_test, y_train, y_test = train_test_split(df_x, df_y, random_state = 47, test_size = 0.3)

In [16]:
svc_linear = svm.SVC(kernel='linear', C=1,gamma='auto').fit(X_train, y_train)

In [17]:
svc_rbf = svm.SVC(kernel='rbf', C=1,gamma='auto').fit(X_train, y_train)

In [18]:
pred_linear=svc_linear.predict(X_test)

In [19]:
pred_rbf=svc_rbf.predict(X_test)

In [20]:
pred_linear

array(['J', 'W', 'F', ..., 'C', 'J', 'I'], dtype=object)

In [21]:
pred_rbf

array(['J', 'W', 'F', ..., 'G', 'J', 'I'], dtype=object)

In [35]:
from sklearn.metrics import accuracy_score

In [22]:
linear_pred_tab=pd.crosstab(y_test,pred_linear)

col_0,A,B,C,D,E,F,G,H,I,J,...,Q,R,S,T,U,V,W,X,Y,Z
letter,,,,,,,,,,,,,,,,,,,,,
A,226,0,0,0,0,0,2,0,0,0,...,0,0,2,0,1,0,0,0,2,0
B,1,212,0,0,2,0,4,4,2,0,...,0,12,3,0,0,2,0,1,0,0
C,0,0,183,1,7,2,4,0,0,0,...,0,0,0,1,2,1,0,0,0,0
D,1,8,0,200,0,1,0,1,0,1,...,0,4,1,1,1,0,0,1,0,0
E,0,1,4,0,193,2,15,0,0,0,...,4,2,9,2,0,0,0,2,0,4
F,2,0,0,1,2,195,1,3,0,2,...,0,0,4,1,1,0,0,0,5,0
G,1,0,12,5,6,3,164,3,0,1,...,12,0,5,0,1,3,1,0,0,0
H,1,4,3,19,0,6,1,155,0,1,...,3,11,0,3,6,0,0,1,0,0
I,0,3,0,4,0,4,0,0,191,6,...,0,0,4,0,0,0,0,2,0,3
J,2,0,0,1,0,4,0,0,11,209,...,0,0,4,0,0,0,0,1,0,6
K,0,0,5,2,3,0,3,3,0,0,...,1,12,0,0,0,0,1,14,0,0
L,1,0,2,5,5,0,6,2,1,0,...,4,0,3,1,0,0,0,0,0,0
M,4,0,0,0,0,0,0,1,0,0,...,0,2,0,0,3,0,4,0,0,0
N,0,2,0,3,0,0,0,6,0,0,...,0,1,0,0,0,1,1,0,0,0
O,3,0,2,7,0,0,3,16,0,1,...,3,0,0,1,1,0,7,0,0,0
P,0,1,0,0,0,17,6,0,0,0,...,0,0,1,0,0,0,0,0,3,0
Q,4,1,2,0,3,1,16,2,0,0,...,200,0,5,0,0,2,1,0,1,0
R,8,5,0,8,2,0,3,3,0,1,...,2,178,0,0,0,1,0,0,0,0
S,1,13,0,0,6,4,3,0,8,1,...,11,1,151,1,0,0,0,0,0,18
T,0,0,0,1,3,6,3,2,0,0,...,1,0,2,210,1,0,0,2,7,5
U,3,0,0,1,0,0,0,7,0,0,...,0,0,0,2,209,0,2,0,0,0
V,2,3,0,0,1,1,2,4,0,0,...,0,0,0,0,0,249,3,0,3,0
W,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,2,0,187,0,0,0
X,0,0,0,0,2,0,3,0,0,0,...,0,2,3,2,0,0,0,196,2,1
Y,1,0,0,0,0,4,0,3,0,0,...,3,0,1,5,0,8,0,1,206,0
Z,0,0,0,2,1,0,0,0,2,7,...,1,0,18,0,0,0,0,1,0,176

In [23]:
rbf_pred_tab=pd.crosstab(y_test,pred_rbf)

In [28]:
agreement_rbf = (pred_rbf == y_test)

10549     True
8938      True
19310     True
4943      True
6604      True
9380     False
5987     False
9707      True
5900      True
6522      True
15834     True
16026     True
1169      True
14186     True
11919     True
15068     True
501       True
5393      True
12358     True
7828      True
4275      True
19541     True
13156     True
12678     True
4443      True
18288     True
17605     True
7608      True
10316     True
17650     True
         ...
14629     True
12715     True
13972     True
12510     True
19363     True
1531      True
12550     True
7742      True
17829     True
11950     True
15410     True
6943      True
6047      True
18350     True
7691      True
12632     True
4492      True
8660      True
4040      True
11854     True
2134      True
16109     True
18102     True
2101      True
509       True
6719      True
8221      True
9595      True
3262      True
18771     True
Name: letter, Length: 6000, dtype: bool

In [32]:
sum(agreement_rbf)

5820

In [33]:
len(agreement_rbf)

6000

In [34]:
type(rbf_pred_tab)

pandas.core.frame.DataFrame

In [38]:
accuracy_score(y_true=y_test,y_pred=pred_rbf)

0.97

In [39]:
accuracy_score(y_true=y_test,y_pred=pred_linear)

0.8485

In [40]:
from sklearn.metrics import confusion_matrix

In [41]:
cnf_matrix=confusion_matrix(y_test,pred_rbf)

In [49]:
FP = cnf_matrix.sum(axis=0) - np.diag(cnf_matrix)  
FN = cnf_matrix.sum(axis=1) - np.diag(cnf_matrix)
TP = np.diag(cnf_matrix)
TN = cnf_matrix.sum() - (FP + FN + TP)

FP = FP.astype(float)
FN = FN.astype(float)
TP = TP.astype(float)
TN = TN.astype(float)
print("TP=",TP, "FP=",FP)

TP= [233. 239. 202. 223. 232. 218. 219. 202. 208. 227. 224. 218. 218. 228.
 222. 243. 240. 209. 222. 244. 236. 257. 202. 218. 229. 207.] FP= [ 1. 17.  5. 22.  7.  7. 15. 21.  8. 10.  5.  0.  3.  6.  6.  3. 10. 11.
  0.  3.  6.  0.  3.  6.  2.  3.]

In [48]:
# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
print("TPR=",TPR)
# Specificity or true negative rate
TNR = TN/(TN+FP) 
print("TNR=",TNR)
# Precision or positive predictive value
PPV = TP/(TP+FP)
# Negative predictive value
NPV = TN/(TN+FN)
# Fall out or false positive rate
FPR = FP/(FP+TN)
# False negative rate
FNR = FN/(TP+FN)
# False discovery rate
FDR = FP/(TP+FP)
# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print("Accuracy=",ACC)

TPR= [0.98728814 0.9755102  0.97115385 0.98672566 0.95473251 0.97321429
 0.96475771 0.88209607 0.95412844 0.95378151 0.94514768 0.96888889
 0.99090909 0.96202532 0.96943231 0.96812749 0.99173554 0.92477876
 1.         0.99591837 0.99578059 0.95539033 0.98536585 0.98642534
 0.98706897 0.99519231]
TNR= [0.99982651 0.99704605 0.99913674 0.99618982 0.99878409 0.99878809
 0.9974017  0.99636112 0.9986164  0.99826449 0.9991324  1.
 0.99948097 0.99895888 0.99896032 0.99947817 0.99826329 0.99809491
 1.         0.99947871 0.99895888 1.         0.99948231 0.99896176
 0.99965326 0.99948204]
Accuracy= [0.99933333 0.99616667 0.99816667 0.99583333 0.997      0.99783333
 0.99616667 0.992      0.997      0.9965     0.997      0.99883333
 0.99916667 0.9975     0.99783333 0.99816667 0.998      0.99533333
 1.         0.99933333 0.99883333 0.998      0.999      0.9985
 0.99916667 0.99933333]

In [ ]:
cnf_matrix = confusion_matrix(y_true, y_prediction)
print(cnf_matrix)
#[[1 1 3]
# [3 2 2]
# [1 3 1]]

FP = cnf_matrix.sum(axis=0) - np.diag(cnf_matrix)  
FN = cnf_matrix.sum(axis=1) - np.diag(cnf_matrix)
TP = np.diag(cnf_matrix)
TN = cnf_matrix.sum() - (FP + FN + TP)

FP = FP.astype(float)
FN = FN.astype(float)
TP = TP.astype(float)
TN = TN.astype(float)

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
# Specificity or true negative rate
TNR = TN/(TN+FP) 
# Precision or positive predictive value
PPV = TP/(TP+FP)
# Negative predictive value
NPV = TN/(TN+FN)
# Fall out or false positive rate
FPR = FP/(FP+TN)
# False negative rate
FNR = FN/(TP+FN)
# False discovery rate
FDR = FP/(TP+FP)
# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)